# Generated by Django 5.0.7 on 2024-08-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paper_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pub_date_dt',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
