# Generated by Django 5.1 on 2024-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='journal_abbreviation',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal_impact_factor',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal_impact_factor_quartile',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
